<a href="https://colab.research.google.com/github/MelihKlc/Machine-Learning/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[ : , 2] = le.fit_transform(X[ : , 2])

One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #bütün featurelara uygulamak zorundayız feature scaling 1 0 0 gibi vektörler olsa bile

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense( units = 6, activation= 'relu' ))  #rectifier kullanıyoruz hidden layerlar için
#unitste seçtiğimiz sayı aslında hidden layerin içinde kaç neuron olacağı

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense( units = 6, activation= 'relu' ))  #herhangi bir hidden layer eklerken hep bu kodu kullanıyoruz.

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense( units = 1, activation= 'sigmoid' ))   #unit 1 seçmemizin sebebi bizim outputumuz binary 0 1 olduğu için 1 outputla çözücez ama mesela birbiriyle alakası olmasaydı A B C gibi 3 tane output çıkarmamız gerekiyordu.
#probabilities almak için sigmoid kullanıyoruz.
#buranın sonunda artık brain oluşmuş oldu ama stupid bir brain çünkü daha train edilmedi

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])   #burda Gradient descent stochastic kullanıyoruz adam parametresi ile
#non binary outcomelarda categorical cross entropy kullanıyoruz loss kısmında
#activation da softmax oluyo nonbinaryde


### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train , batch_size = 32 , epochs = 100) #batch size parameter gives exactly the number of predictions you want to have in the batch to be compared to that same number of real results. classic value of this is 32
# a neural network has to be trained over a certain amount of epocs so has to improve the accuracy over time
#çok küçük seçmediğimiz sürece istediğimiz sayıyı seçebiliriz epochs a çünkü bu bizim modelimizin öğrenmesini sağlayacağı için az öğrenmesini istemeyiz


Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5629 - accuracy: 0.7645
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4818 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4582 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4376 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4215 - accuracy: 0.7969
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8106
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8207
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3945 - accuracy: 0.8291
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3885 - accuracy: 0.8336
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3834 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[ 1 , 0 , 0 , 600 , 1 , 40 , 3 , 60000 ,  2 , 1 , 1 , 50000  ]])) > 0.5)  #her zamanki gibi 2 tane bracket kullanıyoruz predict method 2D array olmak zorunda
#france gibi categorical variable ların encoding halini girmemiz gerekiyor
#başta girdiğimiz 1 , 0 , 0 aslında fransanın encode hali şimdi variable ları tek tek giriyoruz.
#içine girdiğimiz değerler feature scaling e uğramamış değerler olduğu için bunları sc ile scale ediyoruz ve fit eklemiyoruz sadece transform diyoruz çünkü yeni değerler tahmin ederken aynı scale i kullanmamız gerek fit edersek scale i değişiyor.
#sigmoid kullandıgımız icin 1 veya 0 yerine bize probabilites predict edicek
#0.5 threshold ekledik yani %50 nin üstünde çıkarsa true döndürecek o da demek oluyo ki bu adam bankadan ayrılabilir çünkü bu olasılık bize bankadan ayrılma olasılıgını veriyor. false döndürürse bankadan ayrılma ihtimali düşük demek.

1/1 [==============================] - 0s 16ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) #probability outputu binary 0 1 e çevirmek için
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 805us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 201  204]]


0.862